import { Link, useNavigate, useParams, useSearchParams } from 'react-router'
import { useEffect, useState } from 'react'
import { ServingsControl } from '../components/recipes/ServingsControl'
import { scaledIngredientText, selectedServings } from '../domain/recipe/servings'
import { cookingSignal, createCookLog, deleteCookLog, deleteRecipe, generateRecipeGraphic, getRecipe, setFavorite, type Recipe } from '../services/recipes'

export function RecipeDetailPage() {
  const { recipeId = '' } = useParams(); const navigate = useNavigate(); const [searchParams, setSearchParams] = useSearchParams(); const [recipe, setRecipe] = useState<Recipe>(); const [error, setError] = useState<string>(); const [graphicError, setGraphicError] = useState<string>(); const [cookError, setCookError] = useState<string>(); const [confirming, setConfirming] = useState(false); const [generatingGraphic, setGeneratingGraphic] = useState(false); const [cooking, setCooking] = useState(false); const [rating, setRating] = useState(''); const [cookNote, setCookNote] = useState('')
  useEffect(() => { void getRecipe(recipeId).then(setRecipe).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Could not load recipe.')) }, [recipeId])
  if (error) return <section className="recipe-page"><h1>Recipe unavailable</h1><p role="alert">{error}</p><Link to="/">Return to library</Link></section>
  if (!recipe) return <p role="status">Loading recipe…</p>
  const servings = selectedServings(searchParams.get('servings'), recipe.servings)
  const setServings = (value: number) => setSearchParams((current) => { const next = new URLSearchParams(current); if (value === recipe.servings) next.delete('servings'); else next.set('servings', String(value)); return next }, { replace: true })
  const metadata = [servings && `${servings} servings`, recipe.prepMinutes != null && `${recipe.prepMinutes} min prep`, recipe.cookMinutes != null && `${recipe.cookMinutes} min cook`, recipe.totalMinutes != null && `${recipe.totalMinutes} min total`, recipe.cuisine, recipe.category].filter(Boolean)
  const history = cookingSignal(recipe)
  const submitCookLog = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setCooking(true); setCookError(undefined); const value = rating ? Number(rating) : undefined; void createCookLog(recipe.id, { rating: value, note: cookNote || undefined }).then((updated) => { setRecipe(updated); setRating(''); setCookNote('') }).catch((cause: unknown) => setCookError(cause instanceof Error ? cause.message : 'Could not record this cook.')).finally(() => setCooking(false)) }
  return <article className="recipe-page recipe-detail"><p className="eyebrow">{recipe.source.type} recipe</p><h1>{recipe.title}</h1>{recipe.graphicAvailable && <figure className="recipe-graphic"><img src={`/api/recipes/${recipe.id}/graphic`} alt={`AI-generated playful illustration of ${recipe.title}`} /><figcaption>AI menu art — the meal is real; the drama is not.</figcaption></figure>}{recipe.description && <p className="recipe-description">{recipe.description}</p>}{metadata.length > 0 && <p className="recipe-metadata">{metadata.join(' · ')}</p>}{recipe.tags.length > 0 && <p className="recipe-tags">{recipe.tags.join(' · ')}</p>}{history && <p className="recipe-cook-summary">{history}</p>}<div className="recipe-actions"><Link to={`/recipes/${recipe.id}/cook${servings && servings !== recipe.servings ? `?servings=${servings}` : ''}`}>Cook</Link><Link to={`/recipes/${recipe.id}/edit`}>Edit</Link>{!recipe.graphicAvailable && <button type="button" disabled={generatingGraphic} onClick={() => { setGraphicError(undefined); setGeneratingGraphic(true); void generateRecipeGraphic(recipe.id).then(() => getRecipe(recipe.id)).then(setRecipe).catch((cause: unknown) => setGraphicError(cause instanceof Error ? cause.message : 'Could not generate recipe graphic.')).finally(() => setGeneratingGraphic(false)) }}>{generatingGraphic ? 'Generating graphic…' : 'Generate AI menu art (~$0.005)'}</button>}<button type="button" onClick={() => void setFavorite(recipe.id, !recipe.favorite).then(setRecipe).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Could not update favorite.'))}>{recipe.favorite ? 'Unfavorite' : 'Favorite'}</button><button type="button" onClick={() => setConfirming(true)}>Delete</button></div>{graphicError && <p role="alert">{graphicError}</p>}
    {confirming && <section className="delete-confirmation" role="alert"><p>Delete this recipe permanently?</p><button type="button" onClick={() => void deleteRecipe(recipe.id).then(() => navigate('/')).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Could not delete recipe.'))}>Confirm delete</button><button type="button" onClick={() => setConfirming(false)}>Cancel</button></section>}
    <Link to="/">Back to library</Link>
    <section className="recipe-cook-history" aria-labelledby="cook-history-heading"><div><h2 id="cook-history-heading">Cooking history</h2>{history ? <p>{history}</p> : <p>Not cooked yet. Log it when you make this recipe.</p>}</div><form className="recipe-form" onSubmit={submitCookLog}><label>Rating (optional)<select value={rating} onChange={(event) => setRating(event.target.value)} disabled={cooking}><option value="">No rating</option>{[1, 2, 3, 4, 5].map((value) => <option key={value} value={value}>{value} star{value === 1 ? '' : 's'}</option>)}</select></label><label>Cooking note (optional)<textarea value={cookNote} onChange={(event) => setCookNote(event.target.value)} maxLength={1000} disabled={cooking} placeholder="What would you change next time?" /></label><button type="submit" disabled={cooking}>{cooking ? 'Recording…' : 'Cooked it'}</button>{cookError && <p role="alert">{cookError}</p>}</form>{recipe.cookLogs.length > 0 && <ol className="recipe-cook-history__list">{recipe.cookLogs.map((log) => <li key={log.id}><div><strong>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(log.cookedAt))}</strong>{log.rating !== undefined && <span> · {log.rating} / 5 stars</span>}{log.note && <p>{log.note}</p>}</div><button type="button" disabled={cooking} onClick={() => { setCooking(true); setCookError(undefined); void deleteCookLog(recipe.id, log.id).then(setRecipe).catch((cause: unknown) => setCookError(cause instanceof Error ? cause.message : 'Could not remove this cook log.')).finally(() => setCooking(false)) }}>Remove</button></li>)}</ol>}</section>
    {recipe.ingredients.length > 0 && <section><h2>Ingredients</h2>{servings ? <ServingsControl original={recipe.servings!} servings={servings} onChange={setServings} /> : <p className="hint">Add the original servings in Edit to adjust ingredient amounts.</p>}{servings !== undefined && servings !== recipe.servings && <p className="hint">Ingredient amounts are adjusted where possible. Check seasoning and cooking times; instructions still show the original wording.</p>}<ul>{recipe.ingredients.map((ingredient) => <li key={ingredient.id}>{servings ? scaledIngredientText(ingredient.originalText, recipe.servings, servings) : ingredient.originalText}</li>)}</ul></section>}
    {recipe.instructions.length > 0 && <section><h2>Instructions</h2><ol>{recipe.instructions.map((instruction) => <li key={instruction.id}>{instruction.text}</li>)}</ol></section>}
    {recipe.notes && <section><h2>Notes</h2><p>{recipe.notes}</p></section>}
    <section><h2>Source</h2><p>{recipe.source.type === 'url' ? <a href={recipe.source.originalUrl} target="_blank" rel="noreferrer">Imported from {recipe.source.originalUrl}</a> : recipe.source.type === 'pdf' ? `Imported from PDF${recipe.source.sourceName ? `: ${recipe.source.sourceName}` : ''}` : recipe.source.type === 'image' ? `Imported from image${recipe.source.sourceName ? `: ${recipe.source.sourceName}` : ''}` : recipe.source.type === 'text' ? 'Imported from pasted recipe text' : 'Entered manually'}</p></section>
  </article>
}
