import { useEffect, useState } from 'react'
import type { ActivitySummary, BudgetStatus, UsageCapability, UsageDashboard, UsageRange } from '../domain/usage.js'
import { getUsageDashboard } from '../services/usage.js'

const ranges: Array<{ value: UsageRange; label: string }> = [{ value: '7d', label: 'Last 7 days' }, { value: '30d', label: 'Last 30 days' }, { value: 'month', label: 'This month' }]
const number = new Intl.NumberFormat('en-US')
const bytes = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1, notation: 'compact' })
const dollars = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })

export function UsageDashboardPage() {
  const [range, setRange] = useState<UsageRange>('30d')
  const [dashboard, setDashboard] = useState<UsageDashboard>()
  const [error, setError] = useState<{ range: UsageRange; message: string }>()
  useEffect(() => { let active = true; void getUsageDashboard(range).then((result) => active && setDashboard(result)).catch((reason: unknown) => active && setError({ range, message: reason instanceof Error ? reason.message : 'Usage reporting is temporarily unavailable.' })); return () => { active = false } }, [range])
  const isCurrent = dashboard?.range === range
  return <section className="recipe-page usage-page"><div className="page-heading"><div><p className="eyebrow">Owner tools</p><h1>Usage &amp; costs</h1><p className="page-heading__description">A private operational view of Recipeapp activity and optional provider reporting. It is not an invoice.</p></div></div><fieldset className="usage-range"><legend>Reporting period</legend><div>{ranges.map((item) => <button type="button" key={item.value} aria-pressed={range === item.value} onClick={() => setRange(item.value)}>{item.label}</button>)}</div></fieldset>{error?.range === range ? <p className="empty-state" role="alert">{error.message}</p> : !isCurrent ? <p role="status">Loading usage data…</p> : <Dashboard dashboard={dashboard} />}</section>
}

function Dashboard({ dashboard }: { dashboard: UsageDashboard }) {
  return <div className="usage-dashboard"><section><h2>Recipeapp activity</h2><Capability value={dashboard.activity} render={(activity) => <Activity activity={activity} />} /></section><section><h2>Cloudflare usage</h2><div className="usage-card-grid"><Capability value={dashboard.cloudflare.workers} render={(data) => <Metrics title="Workers" values={[['Requests', number.format(data.requests)], ['Errors', number.format(data.errors)]]} />} /><Capability value={dashboard.cloudflare.d1} render={(data) => <Metrics title="D1" values={[['Rows read', number.format(data.rowsRead)], ['Rows written', number.format(data.rowsWritten)], ['Storage', `${bytes.format(data.storageBytes)} B`]]} />} /><Capability value={dashboard.cloudflare.r2} render={(data) => <Metrics title="R2" values={[['Requests', number.format(data.requests)], ['Objects', number.format(data.objectCount)], ['Storage', `${bytes.format(data.storageBytes)} B`]]} />} /></div></section><section><h2>OpenAI usage</h2><Capability value={dashboard.openai} render={(data) => <Metrics title="Usage and actual cost" values={[['Requests', number.format(data.requests)], ['Input tokens', number.format(data.inputTokens)], ['Output tokens', number.format(data.outputTokens)], ['Cost', dollars.format(data.costUsd)]]} />} /></section><section><h2>Monthly budget</h2><Budget value={dashboard.budget} /></section></div>
}

function Capability<T>({ value, render }: { value: UsageCapability<T>; render: (data: T) => React.ReactNode }) { return value.state === 'available' ? <div className="usage-card"><p className="card-kicker">{value.source} · retrieved {new Date(value.retrievedAt).toLocaleString()}</p>{render(value.data)}</div> : <div className="usage-card usage-card--unavailable"><p className="card-kicker">{value.state === 'not_configured' ? 'Not configured' : 'Temporarily unavailable'}</p><p>{value.hint}</p></div> }
function Metrics({ title, values }: { title: string; values: Array<[string, string]> }) { return <><h3>{title}</h3><dl>{values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></> }
function Activity({ activity }: { activity: ActivitySummary }) { return <><Metrics title={`${number.format(activity.recipeCount)} saved recipes`} values={Object.entries(activity.aiAttempts).map(([label, value]) => [`AI ${label} attempts`, number.format(value)])} /><div className="usage-imports"><h3>Imports started</h3>{Object.entries(activity.imports).map(([source, statuses]) => <p key={source}><strong>{source}</strong>: {number.format(Object.values(statuses).reduce((total, value) => total + value, 0))} total · {number.format(statuses.ready)} ready · {number.format(statuses.failed + statuses.no_recipe)} unsuccessful</p>)}</div></> }
function Budget({ value }: { value: BudgetStatus }) { if (value.state === 'not_configured') return <div className="usage-card usage-card--unavailable"><p className="card-kicker">Not configured</p><p>Set a monthly USD budget in Worker configuration to enable this warning.</p></div>; if (value.state === 'unavailable') return <div className="usage-card usage-card--unavailable"><p className="card-kicker">Unavailable</p><p>{value.hint}</p></div>; return <div className={`usage-card usage-card--${value.state}`}><p className="card-kicker">{value.state.replace('_', ' ')}</p><h3>{dollars.format(value.spentUsd)} of {dollars.format(value.budgetUsd)}</h3><p>{value.percent}% of budget used. Warning begins at {value.warningThresholdPercent}%.</p></div> }
